# Reference: https://github.com/tchiotludo/kafkahq/blob/dev/application.example.yml

kafkahq:
  server:
    base-path: ""
    access-log:
      enabled: true
      name: org.kafkahq.log.access
      format: "[Date: {}] [Duration: {} ms] [Url: {} {} {}] [Status: {}] [Ip: {}] [Length: {}] [Port: {}]"

  clients-defaults:
    consumer:
      properties:
        isolation.level: read_committed
        default.api.timeout.ms: 60000

  connections:
    kafka:
      properties:
        bootstrap.servers: "kafka:29092"
      connect:
        url: "http://kafka-connect:8083"

  pagination:
    page-size: 25
    threads: 16

  topic:
    retention: 172800000 # Default retention period when creating topic
    partition: 3 # Default number of partition when creating topic
    replication: 3 # Default number of replicas when creating topic
    default-view: HIDE_INTERNAL
    internal-regexps:
      - "^_.*$"
      - "^.*_schemas$"
      - "^.*connect-config$"
      - "^.*connect-offsets$1"
      - "^.*connect-status$"
    stream-regexps:
      - "^.*-changelog$"
      - "^.*-repartition$"
      - "^.*-rekey$"
    skip-consumer-groups: false # Skip loading consumer group information when showing topics

  topic-data:
    sort: OLDEST
    size: 50
    poll-timeout: 100000
